GET https://book-bucket-server.onrender.com/books HTTP/1.1
Content-Type: application/json

###

POST https://book-bucket-server.onrender.com/books HTTP/1.1
Content-Type: application/json

{
    "title": "kuldeep"
}

###

PUT https://book-bucket-server.onrender.com/books HTTP/1.1
Content-Type: application/json

{
    "title": "new title"
}

###

DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

